### ISSUE TITLE
Release an up-to-date (0.5.35?) CMSMonitoring package to PyPi

### ISSUE THREAD

**Issue by amaltaro** [dmwm/CMSMonitoring#145]
Following this security report:
https://security.snyk.io/vuln/SNYK-PYTHON-STOMPPY-569040

that has been propagated to WMCore, I wonder if you could release a new CMSMonitoring package in PyPi which no longer depends on stomp.py `4.1.21` version. I see the `master` branch already defines stomp.py >= 6.x, so it's probably a matter of packaging and uploading a new version.

Of course, it seems to be a major version upgrade for stomp.py and it would be great if you could check whether this brings in any possible breaking changes on the clients.

**Comment by mrceyhun** [comment]
Hi @amaltaro , yes we've new [StompAMQ7.py](https://github.com/dmwm/CMSMonitoring/blob/master/src/python/CMSMonitoring/StompAMQ7.py) which uses stomp.py version >= 6.1.1, <=7.0 . I'm arranging its release and will inform you when it is ready.

**Comment by mrceyhun** [comment]
Hi @amaltaro , just an update:

New release was uploaded to PyPi.  However, when I checked WMAgent ES index , there will be a difference in "data.metadata" part when you use new release. That's why I'll modify the code according to WMCore needs. Right now, I need to test the full pipeline and that may take a few days because of the expired certificate used in AMQ tests.

I will open WMCore PR for the new changes in StompAMQ.

**Comment by amaltaro** [comment]
That would be really great. We will wait for that, thanks.

**Comment by mrceyhun** [comment]
@amaltaro @vkuznet 
Could you provide the AMQ credentials (username, password) for "wmagent" producer to test. Topic is probably "/topic/cms.jobmon.wmagent". The MONIT flume agent is different for this producer and I would like to test it with the actual one by sending data to "cms-test" broker which will not affect the production data and test data will be in different test index.

**Comment by vkuznet** [comment]
@mrceyhun I don't have it, may be @amaltaro knows, but I doubt it. May be we can use any other producer or setup new test end-point and give it back to Alan which he canplug int WMAgent configuration on test agents.

**Comment by amaltaro** [comment]
@mrceyhun can you please ping me on MM?

**Comment by mrceyhun** [comment]
I put [comment](https://github.com/dmwm/WMCore/pull/11189#issuecomment-1173922182) on the WMCore PR. Latest release can be reached https://pypi.org/project/CMSMonitoring/0.6.4/

**Comment by amaltaro** [comment]
@mrceyhun Hi Ceyhun, I just wanted to confirm that WMCore is now using CMSMonitoring 0.6.4 in production.
However, there is the heartbeat issue that needs to be followed up and a new release created. Should we close this issue out and create a new one for the heartbeat? 

Please let me know if there is anything I can help you with.

**Comment by leggerf** [comment]
@amaltaro we just merged the changes for the heartbeat issue. @mrceyhun is away this week. Next week we'll make a new release with the fix.

**Comment by amaltaro** [comment]
@leggerf Hi Federica, thank you for getting this fixed. I will keep watching this ticket to see when a new release is made available and integrate it into WMCore. Thanks

**Comment by amaltaro** [comment]
@leggerf I just noticed a new release has already been made available to PyPi (0.6.5), according to this PR:
https://github.com/dmwm/CMSMonitoring/pull/155

I am going to give this version a try. Thanks

**Comment by mrceyhun** [comment]
Hi @amaltaro , yes that release(0.6.5) includes heartbeat parameters. I did not inform you before it is merged. You can use either `0.6.5` or `0.6.6` releases. If everything is okay, you can close the issue or I can :)

**Comment by amaltaro** [comment]
@mrceyhun if Lionel is happy with the behaviour of our services using CMSMonitoring 0.6.5, then please go ahead and close it. You can also close this one out and open a new issue in case things need further changes. It's up to you!

**Comment by mrceyhun** [comment]
@amaltaro in the last e-mail thread, Lionel mentioned about some errors but I think they are not related with heart-beat issue. It seems that heart-beat issue is solved. That's why I prefer to close this issue :) 

We can continue to the discussion of other error in the e-mail thread, which I did not much understand from the error log he provided. We need more info to debug. Let me get on with it in the e-mail thread tomorrow.

**Comment by mrceyhun** [comment]
As a summary:

Releases https://pypi.org/project/CMSMonitoring :
- `0.6.1`+ provides `stomp.py==7.0.0` support in `StompAMQ7.py`
- `0.6.5`+ supports user given heart-beat parameters #155 
- `0.6.7`+ fixes overwriting user given logger object #161
