### ISSUE TITLE
Possibility to allow jsonschema version >=3.2

### ISSUE THREAD

**Issue by amaltaro** [dmwm/CMSMonitoring#178]
Hi @mrceyhun @vkuznet , I was going to update the `rucio-clients` package to the latest version (1.29.10 ATM) and noticed that there is actually an incompatilibity of the `jsonschema` versions required by cmsmonitoring and rucio-clients. This is what gets reported by pip:
```
The conflict is caused by:
    cmsmonitoring 0.6.9 depends on jsonschema>=4
    rucio-clients 1.29.10 depends on jsonschema~=3.2.0
```

Given that `rucio-clients` still supports Py2.7, I think there is no way that they can migrate to `jsonschema>=4` at the moment. 

So, I wonder if we could try to relax this version in CMSMonitoring? If you are certain that CMSMonitoring will not work properly on jsonschema=3.2.0, then I am out of options and need to check on how to update the WMCore software stack.

**Comment by mrceyhun** [comment]
@amaltaro Most of the producers don't use json schema validation in which jsonschema is used. I tested with `jsonschema~=3.2.0` without schema validation, it is working fine. I will test with schema enforced producer then create a new release if everything goes well (most probably).

**Comment by mrceyhun** [comment]
Hi @amaltaro here is the new release with requested version `CMSMonitoring==0.6.10` https://pypi.org/project/CMSMonitoring/0.6.10/
Schema validation worked fine.

**Comment by amaltaro** [comment]
Hi Ceyhun, this did the trick and the conflict with rucio-clients is gone. Thank you very much for your prompt feedback om this. From my side, it can now be closed.

**Comment by mrceyhun** [comment]
Thanks Alan, closing.
