### ISSUE TITLE
DBDICT in monit.py unusable

### ISSUE THREAD

**Issue by bockjoo** [dmwm/CMSMonitoring#19]
The only things that are known to me to work is
        'monit_production_cmsjm':7731,
        'monit_production_transfer':8035,

None of the entry in the DBDICT worked for me.
Is monit.py for CMS monitoring admins only?
If not, can you update monit.py?
Thanks,
Bockjoo

**Comment by vkuznet** [comment]
ok, closing the ticket in favor of #20
