### ISSUE TITLE
StompAMQ has a mix of root logger and the upstream one

### ISSUE THREAD

**Issue by amaltaro** [dmwm/CMSMonitoring#29]
Which means some logs are properly recorded - those using `self.logger` - while those using `logging` just go to the default logger object (maybe nowhere).

**Comment by vkuznet** [comment]
Side effect of collaborative effort from multiple StompAMQ version. I'll work on consolidating the loggers. Thanks for reporting this.

**Comment by vkuznet** [comment]
Changes are here: https://github.com/dmwm/CMSMonitoring/pull/30

**Comment by vkuznet** [comment]
I merged #30 which fixes this issue. New tag 0.2.3 and it is uploaded to pypi. Closing this ticket. The other connection issue is in a separate ticket https://github.com/dmwm/WMCore/pull/9214
