### ISSUE TITLE
CMS Job Monitoring with two analysis job type

### ISSUE THREAD

**Issue by amaltaro** [dmwm/CMSMonitoring#32]
If one selects the `Type` drop-down menu in the grafana dashboard
https://monit-grafana.cern.ch/d/000000628/cms-job-monitoring?orgId=11&refresh=15m&var-group_by=ScheddName&var-Tier=All&var-Site=All&var-Type=production&var-CMS_JobType=All&var-CMSPrimaryDataTier=All&var-binning=1h&var-measurement=condor_1h&var-retention_policy=long

we can see it lists `analysis` and `"analysis"` job type. Is it because we have old data in the database, or indeed because something is not getting validated thus creating those 2 variations of job type?

**Comment by vkuznet** [comment]
Alan,
that was discussed in separate thread. Turns out one of the classAds was created with extra quotes. So the issue is known and Stefano/Leonardo/Christian is taking care of it.
